### PR TITLE
Enable continuous delivery

### PR DESCRIPTION
**Pull request by amuniz**
I could not check if GH actions are enabled (as [stated here](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#adding-the-github-action)) because I don't have admin permission in this repository.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by amuniz** [comment]
Cannot add reviewers either /cc @Vlatombe

**Comment by Vlatombe** [comment]
Let me fix that for you

**Comment by Vlatombe** [comment]
@amuniz you're good now. Also https://github.com/jenkins-infra/repository-permissions-updater/pull/2231 for Artifactory.

**Review by aHenryJard — APPROVED** [review]
Looks good, can be tested with https://github.com/jenkinsci/kubernetes-client-api-plugin/pull/129

**Pull request merged**
